import {createSlice} from '@reduxjs/toolkit';

export const SHARED_REDUCER = "sharedDevices";

const MOCK_DEVICE = [
    {
        "status": "MAINTENANCE",
        "name": "Google Pixel 5a",
        "os": "ANDROID",
        "version": "11.0",
        "manufacturer": "Google",
        "model": "Pixel 5a",
        "category": "PHONE",
        "resolution": "1080x2400",
        "deviceHost": "192.168.7.17",
        "errorCode": "NO_ERROR",
        "details": "DAAS is OFFLINE",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "172.30.30.2",
            "172.30.30.3",
            "shared-device2.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "16271JECB04362"
    },
    {
        "status": "MAINTENANCE",
        "name": "Google Pixel 5a",
        "os": "ANDROID",
        "version": "12.0",
        "manufacturer": "Google",
        "model": "Pixel 5a",
        "category": "PHONE",
        "resolution": "1080x2400",
        "deviceHost": "192.168.7.17",
        "errorCode": "NO_ERROR",
        "details": "DAAS is OFFLINE",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "1B151JEG500982"
    },
    {
        "status": "AVAILABLE",
        "name": "samsung SM-G960F",
        "os": "ANDROID",
        "version": "10.0",
        "manufacturer": "samsung",
        "model": "SM-G960F",
        "category": "PHONE",
        "resolution": "1440x2960\nOverride size",
        "deviceHost": "192.168.7.17",
        "devicePort": 33359,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "222112bf1a027ece"
    },
    {
        "status": "AVAILABLE",
        "name": "Google Pixel 3a",
        "os": "ANDROID",
        "version": "11.0",
        "manufacturer": "Google",
        "model": "Pixel 3a",
        "category": "PHONE",
        "resolution": "1080x2220",
        "deviceHost": "192.168.7.17",
        "devicePort": 33366,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "93TAY0FGQ0"
    },
    {
        "status": "MAINTENANCE",
        "name": "Google Pixel XL",
        "os": "ANDROID",
        "version": "10.0",
        "manufacturer": "Google",
        "model": "Pixel XL",
        "category": "PHONE",
        "resolution": "1440x2560",
        "deviceHost": "192.168.7.17",
        "errorCode": "NO_ERROR",
        "details": "DAAS is OFFLINE",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "HT71C0200017"
    },
    {
        "status": "AVAILABLE",
        "name": "samsung SM-T870",
        "os": "ANDROID",
        "version": "11.0",
        "manufacturer": "samsung",
        "model": "SM-T870",
        "category": "TABLET",
        "resolution": "1600x2560",
        "deviceHost": "192.168.2.86",
        "devicePort": 34487,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "R52T100PFTZ"
    },
    {
        "status": "MAINTENANCE",
        "name": "samsung SM-X700",
        "os": "ANDROID",
        "version": "12.0",
        "manufacturer": "samsung",
        "model": "SM-X700",
        "category": "TABLET",
        "resolution": "1600x2560",
        "deviceHost": "192.168.7.17",
        "errorCode": "NO_ERROR",
        "details": "DAAS is OFFLINE",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "R52T306BJPD"
    },
    {
        "status": "AVAILABLE",
        "name": "samsung SM-N970F",
        "os": "ANDROID",
        "version": "11.0",
        "manufacturer": "samsung",
        "model": "SM-N970F",
        "category": "PHONE",
        "resolution": "1080x2280",
        "deviceHost": "192.168.7.17",
        "devicePort": 33360,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "R58M84PR4FF"
    },
    {
        "status": "OFFLINE",
        "name": "samsung SM-G998B",
        "os": "ANDROID",
        "version": "12.0",
        "manufacturer": "samsung",
        "model": "SM-G998B",
        "category": "PHONE",
        "resolution": "1440x3200\nOverride size",
        "deviceHost": "192.168.8.17",
        "region": "Master",
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "R5CRC2Y2YYM"
    },
    {
        "status": "MAINTENANCE",
        "name": "samsung SM-A037F",
        "os": "ANDROID",
        "version": "11.0",
        "manufacturer": "samsung",
        "model": "SM-A037F",
        "category": "PHONE",
        "resolution": "720x1600",
        "deviceHost": "192.168.2.86",
        "errorCode": "NO_ERROR",
        "details": "DAAS is OFFLINE",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "R9PR901HL7V"
    },
    {
        "status": "OFFLINE",
        "name": "samsung SM-A037F",
        "os": "ANDROID",
        "version": "11.0",
        "manufacturer": "samsung",
        "model": "SM-A037F",
        "category": "PHONE",
        "resolution": "720x1600",
        "deviceHost": "192.168.8.17",
        "devicePort": 32976,
        "details": "DAAS is OFFLINE",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "R9PR901HL8J"
    },
    {
        "status": "AVAILABLE",
        "name": "samsung SM-G980F",
        "os": "ANDROID",
        "version": "12.0",
        "manufacturer": "samsung",
        "model": "SM-G980F",
        "category": "PHONE",
        "resolution": "1440x3200\nOverride size",
        "deviceHost": "192.168.7.17",
        "devicePort": 33357,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "releasecloud.experitest.com",
            "shared-device2.experitest.com",
            "192.168.8.44",
            "rndcloud.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "RF8N12AS2BZ"
    },
    {
        "status": "AVAILABLE",
        "name": "samsung SM-G781B",
        "os": "ANDROID",
        "version": "10.0",
        "manufacturer": "samsung",
        "model": "SM-G781B",
        "category": "PHONE",
        "resolution": "1080x2400",
        "deviceHost": "192.168.2.86",
        "devicePort": 34491,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "shared-device2.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "RFCNA0LNBTZ"
    },
    {
        "status": "AVAILABLE",
        "name": "OPPO CPH2251",
        "os": "ANDROID",
        "version": "13.0",
        "manufacturer": "OPPO",
        "model": "CPH2251",
        "category": "PHONE",
        "resolution": "1080x2400",
        "deviceHost": "192.168.7.17",
        "devicePort": 33042,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "rndcloud.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "shared-device2.experitest.com"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "TGCUFIHYS4CML7QW"
    },
    {
        "status": "AVAILABLE",
        "name": "OPPO CPH2065",
        "os": "ANDROID",
        "version": "10.0",
        "manufacturer": "OPPO",
        "model": "CPH2065",
        "category": "PHONE",
        "resolution": "1080x2400",
        "deviceHost": "192.168.7.17",
        "devicePort": 33258,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "172.30.30.2",
            "172.30.30.7",
            "shared-device2.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "ZPQCMZQWX4DMT8ZX"
    },
    {
        "status": "AVAILABLE",
        "name": "Xiaomi Mi MIX 3",
        "os": "ANDROID",
        "version": "10.0",
        "manufacturer": "Xiaomi",
        "model": "Mi MIX 3",
        "category": "PHONE",
        "resolution": "1080x2340",
        "deviceHost": "192.168.7.17",
        "devicePort": 33073,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.2",
            "cloud3.experitest.com",
            "shared-device2.experitest.com",
            "172.30.30.16",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "bd247438"
    },
    {
        "status": "AVAILABLE",
        "name": "OnePlus IN2013",
        "os": "ANDROID",
        "version": "13.0",
        "manufacturer": "OnePlus",
        "model": "IN2013",
        "category": "PHONE",
        "resolution": "1080x2400",
        "deviceHost": "192.168.7.17",
        "devicePort": 33262,
        "errorCode": "NO_ERROR",
        "clouds": [
            "mastercloud.experitest.com",
            "roman-grig",
            "releasecloud.experitest.com",
            "172.30.30.2",
            "cloud3.experitest.com",
            "shared-device2.experitest.com",
            "192.168.8.3",
            "192.168.8.44",
            "yael.experitest.com",
            "rndcloud.experitest.com",
            "yholland.experitest.com",
            "qaopscloud.experitest.com",
            "shared-device1.experitest.com",
            "bern.experitest.com",
            "172.30.30.15",
            "192.168.9.67"
        ],
        "placementConstraints": "tcp://qadockermaster.experitest.local:8080",
        "deviceId": "d278d51a"
    }
]

const sharedDevices = createSlice({
    name: SHARED_REDUCER,
    initialState: {
        sharedDevices: MOCK_DEVICE
    },
    reducers: {
        addSharedDevice: (state, action) => {
            state.sharedDevices.push(action.payload);
        },
        removeSharedDevice: (state, action) => {
            const index = state.sharedDevices.findIndex(d => d.deviceId === action.payload);
            if (index > -1) {
                state.sharedDevices.splice(index, 1);
            }
        }
    }
});

export const addSharedDevice = sharedDevices.actions.addSharedDevice;
export const removeSharedDevice = sharedDevices.actions.removeSharedDevice;
export default sharedDevices.reducer;